import fs from 'fs';
import path from 'path';

export function writeVectorPlugin() {
  return {
    name: 'write-vector',
    configureServer(server) {
      server.middlewares.use('/api/write-vector', async (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end('Method not allowed');
          return;
        }

        let body = '';
        req.on('data', chunk => { body += chunk; });
        req.on('end', async () => {
          try {
            const parsed = JSON.parse(body);
            const outputDir = path.resolve(process.cwd(), 'vector');
            const briefsDir = path.join(outputDir, 'briefs');

            fs.mkdirSync(outputDir, { recursive: true });
            fs.mkdirSync(briefsDir, { recursive: true });

            const filesWritten = [];

            // --- LAYER 1: vector.md ---
            fs.writeFileSync(path.join(outputDir, 'vector.md'), parsed.vectorMd);
            filesWritten.push('vector/vector.md');

            // --- LAYER 2: Data files (JSON + MD companions) ---
            const dataMap = {
              'personas': parsed.data.personas,
              'jtbd': parsed.data.jtbd,
              'pain-points': parsed.data.pain_points,
              'insights': parsed.data.insights,
              'opportunities': parsed.data.opportunities,
              'metrics': parsed.data.success_metrics,
            };

            for (const [name, data] of Object.entries(dataMap)) {
              fs.writeFileSync(
                path.join(outputDir, `${name}.json`),
                JSON.stringify(data, null, 2)
              );
              filesWritten.push(`vector/${name}.json`);

              const md = generateDataMd(name, data);
              fs.writeFileSync(path.join(outputDir, `${name}.md`), md);
              filesWritten.push(`vector/${name}.md`);
            }

            // --- LAYER 3: Briefs ---
            const briefMap = {
              'audience': { title: 'Who We Serve', content: parsed.briefs.audience },
              'needs': { title: 'What They Need', content: parsed.briefs.needs },
              'pain-points': { title: 'What Hurts', content: parsed.briefs.pain_points },
              'insights': { title: 'What We Know', content: parsed.briefs.insights },
              'opportunities': { title: 'Where We See Opportunity', content: parsed.briefs.opportunities },
              'success': { title: 'How We Measure It', content: parsed.briefs.success },
              'summary': { title: 'Executive Summary', content: parsed.briefs.summary },
            };

            for (const [name, brief] of Object.entries(briefMap)) {
              const md = `# ${brief.title}\n\n${brief.content}\n\n---\n*Generated by The Box — Zero Vector Design*\n`;
              fs.writeFileSync(path.join(briefsDir, `${name}.md`), md);
              filesWritten.push(`vector/briefs/${name}.md`);
            }

            // --- Optional: paired DESIGN.md ---
            if (typeof parsed.design === 'string' && parsed.design.trim()) {
              fs.writeFileSync(path.join(outputDir, 'design.md'), parsed.design);
              filesWritten.push('vector/design.md');
            }

            res.setHeader('Content-Type', 'application/json');
            res.end(JSON.stringify({ success: true, files: filesWritten, outputDir }));

          } catch (err) {
            res.statusCode = 500;
            res.end(JSON.stringify({ success: false, error: err.message }));
          }
        });
      });
    }
  };
}

function generateDataMd(name, data) {
  const titles = {
    'personas': 'Personas',
    'jtbd': 'Jobs to Be Done',
    'pain-points': 'Pain Points',
    'insights': 'Insights',
    'opportunities': 'Opportunities',
    'metrics': 'Success Metrics',
  };

  let md = `# ${titles[name] || name}\n\n`;

  if (!Array.isArray(data)) return md + 'No data.\n';

  for (const item of data) {
    if (name === 'personas') {
      md += `## ${item.name}\n`;
      md += `**Role:** ${item.role}\n`;
      md += `**Context:** ${item.context}\n`;
      md += `**Goals:** ${(item.goals || []).join('; ')}\n`;
      md += `**Frustrations:** ${(item.frustrations || []).join('; ')}\n`;
      md += `> "${item.quote}"\n\n`;
    } else if (name === 'jtbd') {
      md += `### [${(item.priority || '').toUpperCase()}] ${item.job}\n`;
      md += `Evidence: ${item.evidence}\n\n`;
    } else if (name === 'pain-points') {
      md += `### [${(item.severity || '').toUpperCase()}] ${item.description}\n`;
      md += `Frequency: ${item.frequency || 'unknown'} | Evidence: ${item.evidence}\n\n`;
    } else if (name === 'insights') {
      md += `### ${item.finding}\n`;
      md += `**Implication:** ${item.implication}\n`;
      md += `**Confidence:** ${item.confidence} | Evidence: ${item.evidence}\n\n`;
    } else if (name === 'opportunities') {
      md += `### [${(item.confidence || '').toUpperCase()}] ${item.description}\n`;
      md += `Addresses: ${(item.addresses || []).join(', ')}\n\n`;
    } else if (name === 'metrics') {
      md += `### ${item.metric}\n`;
      md += `**Target:** ${item.target}\n`;
      md += `Validates: ${(item.addresses || []).join(', ')}\n\n`;
    }
  }

  md += `---\n*Generated by The Box — Zero Vector Design*\n`;
  return md;
}
